# Generated by Django 5.2.3 on 2025-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagengaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagengaleria',
            name='categoria',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('naturaleza', 'Naturaleza')], default='interior', max_length=20),
        ),
    ]
