# Generated by Django 5.2.3 on 2025-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagengaleria_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('categoria', models.CharField(choices=[('naturaleza', 'Naturaleza'), ('pueblo', 'Pueblo'), ('playa', 'Playa'), ('actividad', 'Actividad')], max_length=50)),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
