# Generated by Django 5.2.3 on 2025-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lugarinteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarinteres',
            name='categoria',
            field=models.CharField(choices=[('naturaleza', 'Naturaleza'), ('pueblo', 'Pueblo'), ('playa', 'Playa'), ('actividad', 'Actividad'), ('casa', 'Casa')], max_length=50),
        ),
    ]
