# Generated by Django 5.2.3 on 2025-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movimiento_reserva_alter_lugarinteres_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Dashboard financiero',
                'verbose_name_plural': '📊 Dashboard financiero',
                'managed': False,
            },
        ),
    ]
