# Generated by Django 5.2.3 on 2025-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dashboardfinanciero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motivo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
